version: "3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./config:/config
      - #local/path/to/tv:/tv
      - #local/path/to/movies:/movies
    restart: always